name    'fc-fc_nginx'
version '0.1.0'
source 'https://github.com/ugarcia/fc-provision1.git'
author 'Unai Garcia'
license 'MIT'
summary 'Frontcoder nginx extension module'
description 'Frontcoder nginx extension module'
project_page 'https://github.com/ugarcia/fc-provision1'

## Add dependencies, if any:
dependency 'jfryman/nginx', '>= 0.2.6'
