#!/usr/bin/env ruby
#^syntax detection

forge "https://forgeapi.puppetlabs.com"

mod 'puppetlabs-git', ">=0.3.0"
mod 'puppetlabs-mysql', ">=3.4.0"
mod 'jfryman-nginx', ">=0.2.6"
mod 'nodes-php', ">=0.9.0"
mod 'hunner-wordpress', ">=1.0.0"
